// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Body': string;
  'Cell': string;
  'Column': string;
  'ColumnHeader': string;
  'Content': string;
  'Footer': string;
  'Grid': string;
  'H1': string;
  'Header': string;
  'Input': string;
  'Name': string;
  'P': string;
  'Panel': string;
  'PanelIsHidden': string;
  'Row': string;
  'Text': string;
  'isSorted': string;
}
export const cssExports: CssExports;
export default cssExports;
